// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: meshchat/meshchat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Which frequency slot the group's primary channel lands on. Every node in a
/// group must agree or they cannot hear each other. Carried in invites so a
/// joiner aligns automatically. See implementation guide D-1.
public nonisolated enum Meshchat_MeshMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Primary channel named "MeshChat" -> its own frequency slot. Quietest.
  case groupOnly // = 0

  /// Primary channel name left empty -> firmware derives the same slot as the
  /// public mesh, so public nodes relay our traffic. Content stays private.
  case publicRelay // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .groupOnly
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .groupOnly
    case 1: self = .publicRelay
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .groupOnly: return 0
    case .publicRelay: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Meshchat_MeshMode] = [
    .groupOnly,
    .publicRelay,
  ]

}

/// The inviter's radio settings, so the joiner can align before writing the room.
/// Applied with set_config(lora) only where values differ; region is a hint that
/// never silently overrides a region the joiner has already set.
public nonisolated struct Meshchat_LoRaProfile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var usePreset: Bool = false

  public var modemPreset: Config.LoRaConfig.ModemPreset = .longFast

  /// 0 = derived from the primary channel name.
  public var channelNum: UInt32 = 0

  public var overrideFrequency: Float = 0

  public var region: Config.LoRaConfig.RegionCode = .unset

  public var hopLimit: UInt32 = 0

  public var meshMode: Meshchat_MeshMode = .groupOnly

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Meshchat_Inviter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nodeNum: UInt32 = 0

  /// user.public_key must be 32 bytes; the joiner needs it to send the join
  /// hello as a PKI DM before any NodeInfo has propagated.
  public var user: User {
    get {_user ?? User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  public var hasUser: Bool {self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  public mutating func clearUser() {self._user = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _user: User? = nil
}

/// Everything needed to ask to join a room. Carries no room key material: a
/// photographed code is a request to be let in, not a way in. The keys arrive
/// in a RoomGrant, encrypted to the joiner, once the inviter approves.
public nonisolated struct Meshchat_Invite: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  /// Stable room identity across renames, re-indexing and key rotation.
  public var roomID: UInt32 {
    get {_storage._roomID}
    set {_uniqueStorage()._roomID = newValue}
  }

  /// <= 11 UTF-8 bytes (nanopb limit on ChannelSettings.name).
  public var roomName: String {
    get {_storage._roomName}
    set {_uniqueStorage()._roomName = newValue}
  }

  /// Increments on PSK rotation; lets a joiner overwrite a stale channel.
  public var generation: UInt32 {
    get {_storage._generation}
    set {_uniqueStorage()._generation = newValue}
  }

  public var lora: Meshchat_LoRaProfile {
    get {_storage._lora ?? Meshchat_LoRaProfile()}
    set {_uniqueStorage()._lora = newValue}
  }
  /// Returns true if `lora` has been explicitly set.
  public var hasLora: Bool {_storage._lora != nil}
  /// Clears the value of `lora`. Subsequent reads from it will return its default value.
  public mutating func clearLora() {_uniqueStorage()._lora = nil}

  public var inviter: Meshchat_Inviter {
    get {_storage._inviter ?? Meshchat_Inviter()}
    set {_uniqueStorage()._inviter = newValue}
  }
  /// Returns true if `inviter` has been explicitly set.
  public var hasInviter: Bool {_storage._inviter != nil}
  /// Clears the value of `inviter`. Subsequent reads from it will return its default value.
  public mutating func clearInviter() {_uniqueStorage()._inviter = nil}

  public var inviteID: UInt32 {
    get {_storage._inviteID}
    set {_uniqueStorage()._inviteID = newValue}
  }

  public var issuedAt: UInt32 {
    get {_storage._issuedAt}
    set {_uniqueStorage()._issuedAt = newValue}
  }

  /// What binds the code to one inviter and one moment. Without both, an
  /// invite would be an open door rather than one that closes on its own.
  public var window: UInt32 {
    get {_storage._window}
    set {_uniqueStorage()._window = newValue}
  }

  public var token: Data {
    get {_storage._token}
    set {_uniqueStorage()._token = newValue}
  }

  /// Shown on screen in the QR and never sent over the air; mixed into the key
  /// that protects the grant (Stage 11 Phase 3).
  public var secret: Data {
    get {_storage._secret}
    set {_uniqueStorage()._secret = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Meshchat_MeshChatControl: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var payload: OneOf_Payload? {
    get {return _storage._payload}
    set {_uniqueStorage()._payload = newValue}
  }

  public var joinHello: Meshchat_JoinHello {
    get {
      if case .joinHello(let v)? = _storage._payload {return v}
      return Meshchat_JoinHello()
    }
    set {_uniqueStorage()._payload = .joinHello(newValue)}
  }

  public var rosterEvent: Meshchat_RosterEvent {
    get {
      if case .rosterEvent(let v)? = _storage._payload {return v}
      return Meshchat_RosterEvent()
    }
    set {_uniqueStorage()._payload = .rosterEvent(newValue)}
  }

  public var liveLocationRequest: Meshchat_LiveLocationRequest {
    get {
      if case .liveLocationRequest(let v)? = _storage._payload {return v}
      return Meshchat_LiveLocationRequest()
    }
    set {_uniqueStorage()._payload = .liveLocationRequest(newValue)}
  }

  public var rosterSync: Meshchat_RosterSync {
    get {
      if case .rosterSync(let v)? = _storage._payload {return v}
      return Meshchat_RosterSync()
    }
    set {_uniqueStorage()._payload = .rosterSync(newValue)}
  }

  public var receipt: Meshchat_Receipt {
    get {
      if case .receipt(let v)? = _storage._payload {return v}
      return Meshchat_Receipt()
    }
    set {_uniqueStorage()._payload = .receipt(newValue)}
  }

  public var sealedMessage: Meshchat_SealedMessage {
    get {
      if case .sealedMessage(let v)? = _storage._payload {return v}
      return Meshchat_SealedMessage()
    }
    set {_uniqueStorage()._payload = .sealedMessage(newValue)}
  }

  public var roomText: Meshchat_RoomText {
    get {
      if case .roomText(let v)? = _storage._payload {return v}
      return Meshchat_RoomText()
    }
    set {_uniqueStorage()._payload = .roomText(newValue)}
  }

  public var keyRotation: Meshchat_KeyRotation {
    get {
      if case .keyRotation(let v)? = _storage._payload {return v}
      return Meshchat_KeyRotation()
    }
    set {_uniqueStorage()._payload = .keyRotation(newValue)}
  }

  public var personCard: Meshchat_PersonCard {
    get {
      if case .personCard(let v)? = _storage._payload {return v}
      return Meshchat_PersonCard()
    }
    set {_uniqueStorage()._payload = .personCard(newValue)}
  }

  public var roomGrant: Meshchat_RoomGrant {
    get {
      if case .roomGrant(let v)? = _storage._payload {return v}
      return Meshchat_RoomGrant()
    }
    set {_uniqueStorage()._payload = .roomGrant(newValue)}
  }

  public var sealedDirect: Meshchat_SealedDirect {
    get {
      if case .sealedDirect(let v)? = _storage._payload {return v}
      return Meshchat_SealedDirect()
    }
    set {_uniqueStorage()._payload = .sealedDirect(newValue)}
  }

  /// Only ever inside a SealedMessage. A member's own fix, sealed by their
  /// phone: the radio never broadcasts a position of its own, so nobody
  /// holding a radio or a channel key can read where anyone is.
  public var position: Position {
    get {
      if case .position(let v)? = _storage._payload {return v}
      return Position()
    }
    set {_uniqueStorage()._payload = .position(newValue)}
  }

  /// Only ever inside a SealedMessage. A pin, sealed like the words, so its
  /// place and its lock both answer to the room key rather than the channel.
  public var pin: Waypoint {
    get {
      if case .pin(let v)? = _storage._payload {return v}
      return Waypoint()
    }
    set {_uniqueStorage()._payload = .pin(newValue)}
  }

  /// Only ever inside a SealedMessage: "where are you?". Answered by the
  /// phone with a sealed position, and only while it shares with that room.
  public var positionQuery: Meshchat_PositionQuery {
    get {
      if case .positionQuery(let v)? = _storage._payload {return v}
      return Meshchat_PositionQuery()
    }
    set {_uniqueStorage()._payload = .positionQuery(newValue)}
  }

  /// PKI direct message: a SealedDirect arrived that this phone could not
  /// open, most often because it has not learned the sender's phone key yet.
  /// Says so, rather than leaving the sender believing it was read.
  public var sealedDirectRefused: Meshchat_SealedDirectRefused {
    get {
      if case .sealedDirectRefused(let v)? = _storage._payload {return v}
      return Meshchat_SealedDirectRefused()
    }
    set {_uniqueStorage()._payload = .sealedDirectRefused(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Payload: Equatable, Sendable {
    case joinHello(Meshchat_JoinHello)
    case rosterEvent(Meshchat_RosterEvent)
    case liveLocationRequest(Meshchat_LiveLocationRequest)
    case rosterSync(Meshchat_RosterSync)
    case receipt(Meshchat_Receipt)
    case sealedMessage(Meshchat_SealedMessage)
    case roomText(Meshchat_RoomText)
    case keyRotation(Meshchat_KeyRotation)
    case personCard(Meshchat_PersonCard)
    case roomGrant(Meshchat_RoomGrant)
    case sealedDirect(Meshchat_SealedDirect)
    /// Only ever inside a SealedMessage. A member's own fix, sealed by their
    /// phone: the radio never broadcasts a position of its own, so nobody
    /// holding a radio or a channel key can read where anyone is.
    case position(Position)
    /// Only ever inside a SealedMessage. A pin, sealed like the words, so its
    /// place and its lock both answer to the room key rather than the channel.
    case pin(Waypoint)
    /// Only ever inside a SealedMessage: "where are you?". Answered by the
    /// phone with a sealed position, and only while it shares with that room.
    case positionQuery(Meshchat_PositionQuery)
    /// PKI direct message: a SealedDirect arrived that this phone could not
    /// open, most often because it has not learned the sender's phone key yet.
    /// Says so, rather than leaving the sender believing it was read.
    case sealedDirectRefused(Meshchat_SealedDirectRefused)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// One person's words, or receipts for them, sealed from this phone to theirs.
///
/// Travels as a PKI direct message, so the radios also encrypt it, but it does
/// not rely on them: a radio hands its private key to any phone that connects,
/// so whoever holds either radio could read a message the firmware alone
/// protected. The key here is agreed between the two phones' own keys.
public nonisolated struct Meshchat_SealedDirect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// DirectSeal: a version byte, a nonce, then an encrypted MeshChatControl
  /// (room_text or receipt), bound to sender and recipient.
  public var ciphertext: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Asks one member where they are. Nothing to carry: who asked and in which
/// room are already bound to the seal around it.
public nonisolated struct Meshchat_PositionQuery: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The packet id of a SealedDirect that could not be opened. Carries nothing
/// secret; forging one can only make a sender see a message as not read.
public nonisolated struct Meshchat_SealedDirectRefused: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Who is carrying this radio, as they describe themselves.
///
/// Only ever sent inside a SealedMessage, so it reaches the members of one room
/// and nobody else. On the open mesh a Firepit node still looks like every other
/// node: the radio broadcasts meshtastic.User and none of this.
///
/// A claimed name is decoration, not proof. The node number is the only identity
/// the mesh can attest, so a card is shown beside it rather than instead of it.
public nonisolated struct Meshchat_PersonCard: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// <= 39 UTF-8 bytes, matching a node long name.
  public var name: String = String()

  /// <= 4 UTF-8 bytes, matching a node short name.
  public var tag: String = String()

  /// Chosen identity colour, plus one. 0 means no choice, so the colour is
  /// derived from the node number as before; proto3 cannot tell an unset 0 from
  /// a deliberately chosen slot 0.
  public var colourSlotPlusOne: UInt32 = 0

  /// 33 bytes, a compressed P-256 point: this phone's own key, so a member who
  /// later moves the room to a new key can seal it to this phone rather than
  /// only to the radio. Learned on first sight and kept, so a card cannot
  /// quietly replace somebody's key.
  public var phoneKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A room message with its words already encrypted under the room key, which the
/// radio never holds. Travels on PRIVATE_APP like the rest of this protocol, so
/// clients that are not Firepit ignore it and the radio's own screen does not
/// display it.
public nonisolated struct Meshchat_SealedMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var roomID: UInt32 = 0

  /// Which generation of the room's key sealed it. Members hold two for a
  /// while after a rotation, so a message has to say which rather than leave
  /// the receiver guessing.
  public var generation: UInt32 = 0

  /// SealedText: a version byte, a nonce whose first two bytes say which
  /// hour's key sealed it, then an encrypted MeshChatControl. One envelope for
  /// everything, so words and receipts travel alike and a listener cannot tell
  /// them apart by shape.
  public var ciphertext: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// What somebody typed. Only ever seen inside a SealedMessage.
public nonisolated struct Meshchat_RoomText: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var text: String = String()

  /// Mirrors MeshPacket.reply_id, which cannot be read without the key.
  public var replyID: UInt32 = 0

  /// Mirrors Data.emoji: non-zero makes text one emoji reacting to reply_id,
  /// one of six fixed ones (UX 5.4). Only reactions carry it, so no other
  /// message grows.
  public var emoji: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Who in a room has received a message and who has opened it, batched so one
/// packet answers for many. Sealed under the room key like the messages
/// themselves, or inside a SealedDirect for one person's messages, so an
/// outsider learns neither the conversation nor which messages.
public nonisolated struct Meshchat_Receipt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var roomID: UInt32 = 0

  /// Arrived, not yet opened.
  public var delivered: [UInt32] = []

  /// Opened. Reading implies arrival, so an id is never in both lists.
  public var read: [UInt32] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Joiner -> inviter, as a PKI direct message. Proves which invite was used so
/// the roster can show who vouched for whom. Refused unless it arrives PKI
/// encrypted, addressed to the inviter.
public nonisolated struct Meshchat_JoinHello: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inviteID: UInt32 = 0

  public var token: Data = Data()

  public var generation: UInt32 = 0

  public var appVersion: UInt32 = 0

  /// Exactly 32 bytes: the joiner's radio key. Must equal the key the firmware
  /// decrypted this hello with, so a spoofed hello cannot name somebody else's.
  public var joinerKey: Data = Data()

  /// 33 bytes, a compressed P-256 point: the joiner's phone key. The room's own
  /// key is sealed to it in the grant, so the radios in between cannot read it.
  public var phoneKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Inviter -> joiner, as a PKI direct message, once the inviter has approved.
/// The only thing that carries a room's keys, and it goes to one node that
/// asked for them from arm's length.
public nonisolated struct Meshchat_RoomGrant: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var answer: Meshchat_RoomGrant.Answer = .granted

  public var inviteID: UInt32 = 0

  public var roomID: UInt32 = 0

  public var roomName: String = String()

  /// Exactly 32 bytes. What the radio will encrypt the channel with.
  public var roomPsk: Data = Data()

  /// The generation of the key being handed over, which opens what the room
  /// seals from now on.
  public var generation: UInt32 = 0

  /// What the phone seals words with, sealed in turn to the joiner's phone key
  /// (KeyEnvelope, bound to room_id, generation, the joiner's node and
  /// key_hour). The radio carries it but cannot open it.
  public var sealedKey: Data = Data()

  /// Which hour sealed_key is the key for (hours since 1970, UTC). Room keys
  /// move on every hour, one way, so the joiner gets this hour's and nothing
  /// said before it.
  public var keyHour: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Answer: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case granted // = 0
    case declined // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .granted
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .granted
      case 1: self = .declined
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .granted: return 0
      case .declined: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Meshchat_RoomGrant.Answer] = [
      .granted,
      .declined,
    ]

  }

  public init() {}
}

/// Inviter -> room broadcast, so every member's roster shows the trust chain.
/// JOINED is only believed inside a SealedMessage on the room's own channel.
///
/// KEY_ROTATED is sent sealed under the key being replaced, on the channel key
/// being replaced, before the sender's own radio moves on. A member who then
/// misses their own copy of the new key still hears that the room has gone,
/// and stops talking into a room only a removed member can still read.
public nonisolated struct Meshchat_RosterEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Meshchat_RosterEvent.Kind = .joined

  public var nodeNum: UInt32 = 0

  public var invitedBy: UInt32 = 0

  public var generation: UInt32 = 0

  /// For JOINED: the newcomer's phone key, vouched for by whoever let them in,
  /// so any member can hand them a future room key.
  public var phoneKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Kind: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case joined // = 0
    case keyRotated // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .joined
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .joined
      case 1: self = .keyRotated
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .joined: return 0
      case .keyRotated: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Meshchat_RosterEvent.Kind] = [
      .joined,
      .keyRotated,
    ]

  }

  public init() {}
}

/// Member -> member, as a PKI direct message. Asking only; the recipient's app
/// shows a duration picker and starting to share is always their own decision.
public nonisolated struct Meshchat_LiveLocationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var roomID: UInt32 = 0

  public var suggestedSecs: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Inviter -> joiner, as a PKI direct message, right after a join is proved.
/// Travels inside a SealedMessage under the room key the grant just handed
/// over, so the radios in between cannot read who is in the room.
///
/// Sent directed rather than answering a broadcast "who is here?", because on
/// LoRa every member replying to such a question is a packet storm on each join.
/// The inviter is already in the exchange, so this costs one extra packet.
///
/// Contents are hearsay: the sender is asserting who they believe is present.
/// Receivers must not present a synced entry as strongly as somebody they have
/// actually heard.
public nonisolated struct Meshchat_RosterSync: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var roomID: UInt32 = 0

  /// Truncated to fit one packet, most recently heard first, so a large room
  /// sends its liveliest members rather than failing to send at all.
  public var entries: [Meshchat_RosterEntry] = []

  public var truncated: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Meshchat_RosterEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nodeNum: UInt32 = 0

  public var invitedBy: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// New keys for a room, sent to one member at a time as a PKI direct message so
/// that whoever is being removed simply never receives one. There is no way to
/// take a key back from someone; the room moves to a new one instead.
///
/// Always travels inside a SealedMessage under the key it replaces, so only
/// somebody holding the room's current key can move the room on.
public nonisolated struct Meshchat_KeyRotation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var roomID: UInt32 = 0

  /// Always one more than the generation being replaced.
  public var generation: UInt32 = 0

  /// Exactly 32 bytes. What the radio will encrypt the channel with.
  public var roomPsk: Data = Data()

  public var roomName: String = String()

  /// Who is no longer in the room, so every member's roster agrees and the
  /// reason the key changed can be shown rather than left mysterious.
  public var removed: [UInt32] = []

  /// The new key the phone seals words with, sealed in turn to the recipient's
  /// phone key (KeyEnvelope, bound to room_id, generation, the recipient's
  /// node and key_hour). The radio carries it but cannot open it.
  public var sealedKey: Data = Data()

  /// Which hour sealed_key is the key for (hours since 1970, UTC); see
  /// RoomGrant.key_hour.
  public var keyHour: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "meshchat"

nonisolated extension Meshchat_MeshMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GROUP_ONLY\0\u{1}PUBLIC_RELAY\0")
}

nonisolated extension Meshchat_LoRaProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LoRaProfile"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}use_preset\0\u{3}modem_preset\0\u{3}channel_num\0\u{3}override_frequency\0\u{1}region\0\u{3}hop_limit\0\u{3}mesh_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.usePreset) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.modemPreset) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.channelNum) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.overrideFrequency) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.region) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.hopLimit) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.meshMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.usePreset != false {
      try visitor.visitSingularBoolField(value: self.usePreset, fieldNumber: 1)
    }
    if self.modemPreset != .longFast {
      try visitor.visitSingularEnumField(value: self.modemPreset, fieldNumber: 2)
    }
    if self.channelNum != 0 {
      try visitor.visitSingularUInt32Field(value: self.channelNum, fieldNumber: 3)
    }
    if self.overrideFrequency.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.overrideFrequency, fieldNumber: 4)
    }
    if self.region != .unset {
      try visitor.visitSingularEnumField(value: self.region, fieldNumber: 5)
    }
    if self.hopLimit != 0 {
      try visitor.visitSingularUInt32Field(value: self.hopLimit, fieldNumber: 6)
    }
    if self.meshMode != .groupOnly {
      try visitor.visitSingularEnumField(value: self.meshMode, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_LoRaProfile, rhs: Meshchat_LoRaProfile) -> Bool {
    if lhs.usePreset != rhs.usePreset {return false}
    if lhs.modemPreset != rhs.modemPreset {return false}
    if lhs.channelNum != rhs.channelNum {return false}
    if lhs.overrideFrequency != rhs.overrideFrequency {return false}
    if lhs.region != rhs.region {return false}
    if lhs.hopLimit != rhs.hopLimit {return false}
    if lhs.meshMode != rhs.meshMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_Inviter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Inviter"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}node_num\0\u{1}user\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.nodeNum) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.nodeNum != 0 {
      try visitor.visitSingularUInt32Field(value: self.nodeNum, fieldNumber: 1)
    }
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_Inviter, rhs: Meshchat_Inviter) -> Bool {
    if lhs.nodeNum != rhs.nodeNum {return false}
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_Invite: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Invite"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{3}room_id\0\u{3}room_name\0\u{2}\u{3}generation\0\u{1}lora\0\u{1}inviter\0\u{3}invite_id\0\u{3}issued_at\0\u{1}window\0\u{1}token\0\u{2}\u{2}secret\0\u{b}room_psk\0\u{b}firepit_key\0\u{b}position_precision\0\u{c}\u{4}\u{1}\u{c}\u{5}\u{1}\u{c}\u{d}\u{1}")

  fileprivate class _StorageClass {
    var _version: UInt32 = 0
    var _roomID: UInt32 = 0
    var _roomName: String = String()
    var _generation: UInt32 = 0
    var _lora: Meshchat_LoRaProfile? = nil
    var _inviter: Meshchat_Inviter? = nil
    var _inviteID: UInt32 = 0
    var _issuedAt: UInt32 = 0
    var _window: UInt32 = 0
    var _token: Data = Data()
    var _secret: Data = Data()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _roomID = source._roomID
      _roomName = source._roomName
      _generation = source._generation
      _lora = source._lora
      _inviter = source._inviter
      _inviteID = source._inviteID
      _issuedAt = source._issuedAt
      _window = source._window
      _token = source._token
      _secret = source._secret
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._version) }()
        case 2: try { try decoder.decodeSingularFixed32Field(value: &_storage._roomID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._roomName) }()
        case 6: try { try decoder.decodeSingularUInt32Field(value: &_storage._generation) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._lora) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._inviter) }()
        case 9: try { try decoder.decodeSingularFixed32Field(value: &_storage._inviteID) }()
        case 10: try { try decoder.decodeSingularUInt32Field(value: &_storage._issuedAt) }()
        case 11: try { try decoder.decodeSingularUInt32Field(value: &_storage._window) }()
        case 12: try { try decoder.decodeSingularBytesField(value: &_storage._token) }()
        case 14: try { try decoder.decodeSingularBytesField(value: &_storage._secret) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._version != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._version, fieldNumber: 1)
      }
      if _storage._roomID != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._roomID, fieldNumber: 2)
      }
      if !_storage._roomName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._roomName, fieldNumber: 3)
      }
      if _storage._generation != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._generation, fieldNumber: 6)
      }
      try { if let v = _storage._lora {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._inviter {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      if _storage._inviteID != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._inviteID, fieldNumber: 9)
      }
      if _storage._issuedAt != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._issuedAt, fieldNumber: 10)
      }
      if _storage._window != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._window, fieldNumber: 11)
      }
      if !_storage._token.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._token, fieldNumber: 12)
      }
      if !_storage._secret.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._secret, fieldNumber: 14)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_Invite, rhs: Meshchat_Invite) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._roomID != rhs_storage._roomID {return false}
        if _storage._roomName != rhs_storage._roomName {return false}
        if _storage._generation != rhs_storage._generation {return false}
        if _storage._lora != rhs_storage._lora {return false}
        if _storage._inviter != rhs_storage._inviter {return false}
        if _storage._inviteID != rhs_storage._inviteID {return false}
        if _storage._issuedAt != rhs_storage._issuedAt {return false}
        if _storage._window != rhs_storage._window {return false}
        if _storage._token != rhs_storage._token {return false}
        if _storage._secret != rhs_storage._secret {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_MeshChatControl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MeshChatControl"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{3}join_hello\0\u{3}roster_event\0\u{3}live_location_request\0\u{3}roster_sync\0\u{1}receipt\0\u{3}sealed_message\0\u{3}room_text\0\u{3}key_rotation\0\u{3}person_card\0\u{3}room_grant\0\u{3}sealed_direct\0\u{1}position\0\u{1}pin\0\u{3}position_query\0\u{3}sealed_direct_refused\0")

  fileprivate class _StorageClass {
    var _version: UInt32 = 0
    var _payload: Meshchat_MeshChatControl.OneOf_Payload?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _payload = source._payload
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._version) }()
        case 2: try {
          var v: Meshchat_JoinHello?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .joinHello(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .joinHello(v)
          }
        }()
        case 3: try {
          var v: Meshchat_RosterEvent?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .rosterEvent(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .rosterEvent(v)
          }
        }()
        case 4: try {
          var v: Meshchat_LiveLocationRequest?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .liveLocationRequest(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .liveLocationRequest(v)
          }
        }()
        case 5: try {
          var v: Meshchat_RosterSync?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .rosterSync(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .rosterSync(v)
          }
        }()
        case 6: try {
          var v: Meshchat_Receipt?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .receipt(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .receipt(v)
          }
        }()
        case 7: try {
          var v: Meshchat_SealedMessage?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .sealedMessage(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .sealedMessage(v)
          }
        }()
        case 8: try {
          var v: Meshchat_RoomText?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .roomText(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .roomText(v)
          }
        }()
        case 9: try {
          var v: Meshchat_KeyRotation?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .keyRotation(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .keyRotation(v)
          }
        }()
        case 10: try {
          var v: Meshchat_PersonCard?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .personCard(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .personCard(v)
          }
        }()
        case 11: try {
          var v: Meshchat_RoomGrant?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .roomGrant(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .roomGrant(v)
          }
        }()
        case 12: try {
          var v: Meshchat_SealedDirect?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .sealedDirect(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .sealedDirect(v)
          }
        }()
        case 13: try {
          var v: Position?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .position(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .position(v)
          }
        }()
        case 14: try {
          var v: Waypoint?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .pin(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .pin(v)
          }
        }()
        case 15: try {
          var v: Meshchat_PositionQuery?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .positionQuery(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .positionQuery(v)
          }
        }()
        case 16: try {
          var v: Meshchat_SealedDirectRefused?
          var hadOneofValue = false
          if let current = _storage._payload {
            hadOneofValue = true
            if case .sealedDirectRefused(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._payload = .sealedDirectRefused(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._version != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._version, fieldNumber: 1)
      }
      switch _storage._payload {
      case .joinHello?: try {
        guard case .joinHello(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }()
      case .rosterEvent?: try {
        guard case .rosterEvent(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }()
      case .liveLocationRequest?: try {
        guard case .liveLocationRequest(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }()
      case .rosterSync?: try {
        guard case .rosterSync(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }()
      case .receipt?: try {
        guard case .receipt(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .sealedMessage?: try {
        guard case .sealedMessage(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case .roomText?: try {
        guard case .roomText(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }()
      case .keyRotation?: try {
        guard case .keyRotation(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }()
      case .personCard?: try {
        guard case .personCard(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      }()
      case .roomGrant?: try {
        guard case .roomGrant(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }()
      case .sealedDirect?: try {
        guard case .sealedDirect(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }()
      case .position?: try {
        guard case .position(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      }()
      case .pin?: try {
        guard case .pin(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      }()
      case .positionQuery?: try {
        guard case .positionQuery(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      }()
      case .sealedDirectRefused?: try {
        guard case .sealedDirectRefused(let v)? = _storage._payload else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_MeshChatControl, rhs: Meshchat_MeshChatControl) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._payload != rhs_storage._payload {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_SealedDirect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SealedDirect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ciphertext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_SealedDirect, rhs: Meshchat_SealedDirect) -> Bool {
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_PositionQuery: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PositionQuery"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_PositionQuery, rhs: Meshchat_PositionQuery) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_SealedDirectRefused: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SealedDirectRefused"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.requestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed32Field(value: self.requestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_SealedDirectRefused, rhs: Meshchat_SealedDirectRefused) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_PersonCard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PersonCard"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}tag\0\u{3}colour_slot_plus_one\0\u{3}phone_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.tag) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.colourSlotPlusOne) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.phoneKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.tag.isEmpty {
      try visitor.visitSingularStringField(value: self.tag, fieldNumber: 2)
    }
    if self.colourSlotPlusOne != 0 {
      try visitor.visitSingularUInt32Field(value: self.colourSlotPlusOne, fieldNumber: 3)
    }
    if !self.phoneKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.phoneKey, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_PersonCard, rhs: Meshchat_PersonCard) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs.colourSlotPlusOne != rhs.colourSlotPlusOne {return false}
    if lhs.phoneKey != rhs.phoneKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_SealedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SealedMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}room_id\0\u{1}ciphertext\0\u{1}generation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.generation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 1)
    }
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 2)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt32Field(value: self.generation, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_SealedMessage, rhs: Meshchat_SealedMessage) -> Bool {
    if lhs.roomID != rhs.roomID {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RoomText: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomText"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}reply_id\0\u{1}emoji\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.replyID) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.emoji) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    if self.replyID != 0 {
      try visitor.visitSingularFixed32Field(value: self.replyID, fieldNumber: 2)
    }
    if self.emoji != 0 {
      try visitor.visitSingularUInt32Field(value: self.emoji, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_RoomText, rhs: Meshchat_RoomText) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.replyID != rhs.replyID {return false}
    if lhs.emoji != rhs.emoji {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_Receipt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Receipt"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}room_id\0\u{1}delivered\0\u{1}read\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 2: try { try decoder.decodeRepeatedFixed32Field(value: &self.delivered) }()
      case 3: try { try decoder.decodeRepeatedFixed32Field(value: &self.read) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 1)
    }
    if !self.delivered.isEmpty {
      try visitor.visitPackedFixed32Field(value: self.delivered, fieldNumber: 2)
    }
    if !self.read.isEmpty {
      try visitor.visitPackedFixed32Field(value: self.read, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_Receipt, rhs: Meshchat_Receipt) -> Bool {
    if lhs.roomID != rhs.roomID {return false}
    if lhs.delivered != rhs.delivered {return false}
    if lhs.read != rhs.read {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_JoinHello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".JoinHello"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}invite_id\0\u{1}token\0\u{1}generation\0\u{3}app_version\0\u{3}joiner_key\0\u{3}phone_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.inviteID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.token) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.generation) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.appVersion) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.joinerKey) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.phoneKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.inviteID != 0 {
      try visitor.visitSingularFixed32Field(value: self.inviteID, fieldNumber: 1)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularBytesField(value: self.token, fieldNumber: 2)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt32Field(value: self.generation, fieldNumber: 3)
    }
    if self.appVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.appVersion, fieldNumber: 4)
    }
    if !self.joinerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.joinerKey, fieldNumber: 5)
    }
    if !self.phoneKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.phoneKey, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_JoinHello, rhs: Meshchat_JoinHello) -> Bool {
    if lhs.inviteID != rhs.inviteID {return false}
    if lhs.token != rhs.token {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.appVersion != rhs.appVersion {return false}
    if lhs.joinerKey != rhs.joinerKey {return false}
    if lhs.phoneKey != rhs.phoneKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RoomGrant: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoomGrant"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}answer\0\u{3}invite_id\0\u{3}room_id\0\u{3}room_name\0\u{3}room_psk\0\u{2}\u{2}generation\0\u{4}\u{2}sealed_key\0\u{3}key_hour\0\u{b}firepit_key\0\u{b}position_precision\0\u{c}\u{6}\u{1}\u{c}\u{8}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.answer) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.inviteID) }()
      case 3: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.roomName) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.roomPsk) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.generation) }()
      case 9: try { try decoder.decodeSingularBytesField(value: &self.sealedKey) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.keyHour) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.answer != .granted {
      try visitor.visitSingularEnumField(value: self.answer, fieldNumber: 1)
    }
    if self.inviteID != 0 {
      try visitor.visitSingularFixed32Field(value: self.inviteID, fieldNumber: 2)
    }
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 3)
    }
    if !self.roomName.isEmpty {
      try visitor.visitSingularStringField(value: self.roomName, fieldNumber: 4)
    }
    if !self.roomPsk.isEmpty {
      try visitor.visitSingularBytesField(value: self.roomPsk, fieldNumber: 5)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt32Field(value: self.generation, fieldNumber: 7)
    }
    if !self.sealedKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.sealedKey, fieldNumber: 9)
    }
    if self.keyHour != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyHour, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_RoomGrant, rhs: Meshchat_RoomGrant) -> Bool {
    if lhs.answer != rhs.answer {return false}
    if lhs.inviteID != rhs.inviteID {return false}
    if lhs.roomID != rhs.roomID {return false}
    if lhs.roomName != rhs.roomName {return false}
    if lhs.roomPsk != rhs.roomPsk {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.sealedKey != rhs.sealedKey {return false}
    if lhs.keyHour != rhs.keyHour {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RoomGrant.Answer: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GRANTED\0\u{1}DECLINED\0")
}

nonisolated extension Meshchat_RosterEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{3}node_num\0\u{3}invited_by\0\u{1}generation\0\u{3}phone_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.nodeNum) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.invitedBy) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.generation) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.phoneKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.kind != .joined {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 1)
    }
    if self.nodeNum != 0 {
      try visitor.visitSingularUInt32Field(value: self.nodeNum, fieldNumber: 2)
    }
    if self.invitedBy != 0 {
      try visitor.visitSingularUInt32Field(value: self.invitedBy, fieldNumber: 3)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt32Field(value: self.generation, fieldNumber: 4)
    }
    if !self.phoneKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.phoneKey, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_RosterEvent, rhs: Meshchat_RosterEvent) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.nodeNum != rhs.nodeNum {return false}
    if lhs.invitedBy != rhs.invitedBy {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.phoneKey != rhs.phoneKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RosterEvent.Kind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0JOINED\0\u{1}KEY_ROTATED\0")
}

nonisolated extension Meshchat_LiveLocationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LiveLocationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}room_id\0\u{3}suggested_secs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.suggestedSecs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 1)
    }
    if self.suggestedSecs != 0 {
      try visitor.visitSingularUInt32Field(value: self.suggestedSecs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_LiveLocationRequest, rhs: Meshchat_LiveLocationRequest) -> Bool {
    if lhs.roomID != rhs.roomID {return false}
    if lhs.suggestedSecs != rhs.suggestedSecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RosterSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterSync"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}room_id\0\u{1}entries\0\u{1}truncated\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.truncated) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 1)
    }
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 2)
    }
    if self.truncated != false {
      try visitor.visitSingularBoolField(value: self.truncated, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_RosterSync, rhs: Meshchat_RosterSync) -> Bool {
    if lhs.roomID != rhs.roomID {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.truncated != rhs.truncated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_RosterEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}node_num\0\u{3}invited_by\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.nodeNum) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.invitedBy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.nodeNum != 0 {
      try visitor.visitSingularUInt32Field(value: self.nodeNum, fieldNumber: 1)
    }
    if self.invitedBy != 0 {
      try visitor.visitSingularUInt32Field(value: self.invitedBy, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_RosterEntry, rhs: Meshchat_RosterEntry) -> Bool {
    if lhs.nodeNum != rhs.nodeNum {return false}
    if lhs.invitedBy != rhs.invitedBy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Meshchat_KeyRotation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyRotation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}room_id\0\u{1}generation\0\u{3}room_psk\0\u{4}\u{2}room_name\0\u{1}removed\0\u{3}sealed_key\0\u{3}key_hour\0\u{b}firepit_key\0\u{c}\u{4}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.roomID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.generation) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.roomPsk) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.roomName) }()
      case 6: try { try decoder.decodeRepeatedFixed32Field(value: &self.removed) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.sealedKey) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.keyHour) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.roomID != 0 {
      try visitor.visitSingularFixed32Field(value: self.roomID, fieldNumber: 1)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt32Field(value: self.generation, fieldNumber: 2)
    }
    if !self.roomPsk.isEmpty {
      try visitor.visitSingularBytesField(value: self.roomPsk, fieldNumber: 3)
    }
    if !self.roomName.isEmpty {
      try visitor.visitSingularStringField(value: self.roomName, fieldNumber: 5)
    }
    if !self.removed.isEmpty {
      try visitor.visitPackedFixed32Field(value: self.removed, fieldNumber: 6)
    }
    if !self.sealedKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.sealedKey, fieldNumber: 7)
    }
    if self.keyHour != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyHour, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Meshchat_KeyRotation, rhs: Meshchat_KeyRotation) -> Bool {
    if lhs.roomID != rhs.roomID {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.roomPsk != rhs.roomPsk {return false}
    if lhs.roomName != rhs.roomName {return false}
    if lhs.removed != rhs.removed {return false}
    if lhs.sealedKey != rhs.sealedKey {return false}
    if lhs.keyHour != rhs.keyHour {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
