#!/usr/bin/env python3
"""Copies the glyphs both apps must draw identically from Android into the iOS asset catalogue.

People compare these across phones: a room's icon, a radio's role and a dropped pin are meant to look the same to
every member, whichever platform they use. Android's vector drawables are the source; this writes each one as an SVG
template image in ios/Firepit/Assets.xcassets/Glyphs, which SwiftUI tints like a symbol. The rest of the iOS icons
stay SF Symbols, as the platform expects.

Run from the repository root after changing any of the drawables below:
    scripts/sync-ios-glyphs.py          write the image sets
    scripts/sync-ios-glyphs.py --check  exit 1 if any image set is missing or out of date
"""
import json
import pathlib
import sys
import xml.etree.ElementTree as ET

DRAWABLES = pathlib.Path("android/core/designsystem/src/main/res/drawable")
GLYPHS = pathlib.Path("ios/Firepit/Assets.xcassets/Glyphs")
SHARED = [
    "ic_room_tent", "ic_room_trail", "ic_room_car", "ic_room_music",
    "ic_room_flag", "ic_room_house", "ic_room_star", "ic_room_heart",
    "ic_role_personal", "ic_role_base", "ic_role_router",
    "ic_pin",
]
ANDROID = "{http://schemas.android.com/apk/res/android}"


def colour(value):
    """Android's #AARRGGBB or #RRGGBB as SVG; fully transparent is no paint at all."""
    if not value:
        return None
    digits = value.lstrip("#")
    if len(digits) == 8:
        return None if digits[:2] == "00" else "#" + digits[2:]
    return "#" + digits


def svg(drawable: pathlib.Path) -> str:
    root = ET.parse(drawable).getroot()
    if root.find("group") is not None:
        sys.exit(f"{drawable}: groups are not supported; flatten the drawable")
    width, height = root.get(ANDROID + "viewportWidth"), root.get(ANDROID + "viewportHeight")
    paths = []
    for path in root.iter("path"):
        attributes = [f'd="{path.get(ANDROID + "pathData")}"', f'fill="{colour(path.get(ANDROID + "fillColor")) or "none"}"']
        if path.get(ANDROID + "fillType") == "evenOdd":
            attributes.append('fill-rule="evenodd"')
        stroke = colour(path.get(ANDROID + "strokeColor"))
        if stroke:
            attributes += [
                f'stroke="{stroke}"',
                f'stroke-width="{path.get(ANDROID + "strokeWidth") or 1}"',
                f'stroke-linecap="{(path.get(ANDROID + "strokeLineCap") or "butt").lower()}"',
                f'stroke-linejoin="{(path.get(ANDROID + "strokeLineJoin") or "miter").lower()}"',
            ]
        paths.append(f"  <path {' '.join(attributes)}/>")
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
        f"  <!-- Generated by scripts/sync-ios-glyphs.py from {drawable.as_posix()}; edit that instead. -->\n"
        + "\n".join(paths)
        + "\n</svg>\n"
    )


def contents(name: str) -> str:
    return json.dumps(
        {
            "images": [{"filename": f"{name}.svg", "idiom": "universal"}],
            "info": {"author": "xcode", "version": 1},
            "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"},
        },
        indent=2,
    ) + "\n"


def main() -> None:
    check = "--check" in sys.argv[1:]
    expected = {GLYPHS / "Contents.json": json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n"}
    for drawable in SHARED:
        name = drawable.removeprefix("ic_").replace("_", "-")
        folder = GLYPHS / f"{name}.imageset"
        expected[folder / f"{name}.svg"] = svg(DRAWABLES / f"{drawable}.xml")
        expected[folder / "Contents.json"] = contents(name)
    stale = [path for path, text in expected.items() if not path.exists() or path.read_text() != text]
    if check:
        for path in stale:
            print(f"out of date: {path}")
        sys.exit(1 if stale else 0)
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected[path])
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
