// Firepit's own protobufs (invite payload, control port 300) generated by Wire from ../../protos/meshchat.proto.
// Kept as a plain JVM module so codegen never depends on Android Gradle plugin internals.
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.wire)
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

wire {
    sourcePath {
        srcDir("../../protos")
        include("meshchat.proto")
    }
    kotlin {}
}
